name: Create Release and Update Repository

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: ReiwaTech/DalamudPluginRepo/.github/workflows/reusable_create_release.yml@master
    with:
      internal_name: InventoryTools
      solution_name: InventoryTools
      build_configuration: Release
      personal_plugin_repo: ReiwaTech/DalamudPluginRepo
      personal_plugin_repo_branch: master
      output_directory: ./bin/Release
    secrets: inherit
